### ISSUE TITLE
Integrate with web3 for transaction signing in the frontend

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/offline-pay-with-celo#26]
- If CELO is selected as the send option, set state to CELO
- Then use https://docs.celo.org/developer-guide/dappkit/usage to enable users to sign in to their wallet
- Then have them sign a transaction based on the input fields

Depends on https://github.com/Chimoney/offline-pay-with-crypto/issues/24

Resources:
- https://docs.celo.org/developer-guide/dappkit/usage
- https://web3js.readthedocs.io/en/v1.3.0/

**Comment by uchibeke** [comment]
Hey @adebayoileri, have you seen https://github.com/celo-org/use-contractkit?

With that, you can make a payment by:
- First checking if user selected CELO or cUSD
- Use the form fields to generate the transactions and prompt user to sign as per https://github.com/celo-org/use-contractkit#get-a-connected-account

And for users transferring directly, they can still use the QR code.

**Comment by adebayoileri** [comment]
Yes, currently working with this. i've being able to get the user to sign in via celo wallet and metamask. Will jump on transfer part 👍🏼

**Comment by uchibeke** [comment]
Hi Bayo, I will work on this and complete it so people can make payments from Metamask or Celo wallet
