### ISSUE TITLE
Extend payment link generator

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/offline-pay-with-celo#43]
Extend the payment link generator to do:
- Data validation
- Include suggest exchange rates so that if someone first picks Celo, and then decides to add cUSD or another currency, we recommend the cUSD valud of the first Celo value

Think of the payment link generator as the merchant-facing experience but completely open-source and decentralized.

Also, if possible, validate the address or at least tell them to confirm it

**Comment by uchibeke** [comment]
@adebayoileri  here are some exchange rate APIs:

- https://developer.coingate.com/docs/list-rates
- https://developer.coingate.com/docs/get-rate

- https://developers.coinbase.com/api/v2#exchange-rates


- https://docs.sendwyre.com/reference/getexchangerates

- https://documenter.getpostman.com/view/6895769/S11RKvNp


- https://docs.cryptoapis.io/rest-apis/crypto-market-data-apis/index#exchange-rates

- https://www.blockchain.com/api/exchange_rates_api


To make this interesting and also to prevent one point of failure, consider calling 3 APIs to get the rate, then use that to create an object that maps fiat to currencies and handles failures. If one of the APIs fails, use the remaining 2 and take the average rate.

**Comment by adebayoileri** [comment]
Awesome 👍

**Comment by uchibeke** [comment]
hi Bayo, for the exchange rate, could you use https://coinmarketcap.com/ API, please?

Let's start with the free version and we will get them to upgrade us

This issue is related to https://github.com/Chimoney/offline-pay-with-celo/issues/47
