### ISSUE TITLE
Form field validation and responsiveness

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/offline-pay-with-celo#47]
- Wallet address form should be valid and responsive
- Also, if params are passed in the URL, fill the form with params and redirect to checkout
- Confirm that you can scan the generated QR code with the Valora app or any app that supports celo
- You could alternatively download the QR code and use https://celowallet.app/

**Comment by uchibeke** [comment]
@adebayoileri were you able to figure out the QR generator for celo?

**Comment by adebayoileri** [comment]
> @adebayoileri were you able to figure out the QR generator for celo?

Not yet. Don't seem to get the format they expect the QRcode to hold i.e(the content)?

**Comment by adebayoileri** [comment]
But from the contract kit modal, there's a Valora QRCode option pointing to the wallet address. But, I'm still on making it work 👍🏼
